### ISSUE TITLE
Standardise json formatting for attacks

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/AI-SDC#109]
and maybe also create a 'how-to' doc or similar for people adding future new attacks

**Comment by shahzadmumtaz22** [comment]
The PRs (worst-case https://github.com/AI-SDC/AI-SDC/pull/105 and LIRA https://github.com/AI-SDC/AI-SDC/pull/118) produces standardised output for metrics though LIRA has only one run whereas worst-case has many repetitions. 

The variable names standardisation in the metadata section both for worst-case and LIRA scenarios (not for all variable but where possible) is also done and is part of another PR https://github.com/AI-SDC/AI-SDC/pull/120
