### ISSUE TITLE
`attack.report.create_mia_report` needs to be made properly compatible with new output format

### ISSUE THREAD

**Issue by simonrnss** [AI-SDC/AI-SDC#125]
The method `create_mia_report` in `aisdc.attacks.report.py` has had an elastoplast stuck over it to ensure that the example will create a report.

However, this needs a proper fix now that the output format has been modified. Please ensure that this is:
1. Accessing the output structure correctly.
2. Exposing the correct details (including the roc plot)
3. Covered by tests

**Comment by simonrnss** [comment]
**UPDATE**:
1. This is already fixed in one of @shahzadmumtaz22's PRs, so we might just be able to close this issue once they have been merged.
2. Ultimately, as @rpreen points out, this should be done seperately -- i.e. from the json, regardless of json source. We should therefore put this one on hold, potentially close it when the prs have been merged and create a more detailed issue to cover pdf creation once #126 has been done

**Comment by jim-smith** [comment]
@simonrnss @yolaj-nhs @rpreen moving this to sprint 3 - I think te jsut need a second pair of eyes to make sure that the sticking plaster has been removed and the injury dealt with.

**Comment by jim-smith** [comment]
closed by consent
