### ISSUE TITLE
Output module output tests

### ISSUE THREAD

**Issue by simonrnss** [AI-SDC/AI-SDC#129]
The tests covering the output modules determine that the modules will consume dictionaries without error. We should aim to make these more complete and actually test their output.

Completion of #126 will result in one or (ideally) more .json files that can be stored within the repository as examples and also for unit testing. With these, it will be possible to:

1. Test the outputs of the modules for the correct answers
2. Ensure that future changes don't unwittinly change the output format (and potentially break downstream tools)

Depends on completion of #126

**Comment by jim-smith** [comment]
@simonrnss in the safe models I use dictdiffer which does exactly. this (and more)
