### ISSUE TITLE
SAFEmodels should report generalisation errors

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/AI-SDC#150]
Generalisation errors are showing to be a good lower bound on inference risk.
So it would make sense for the safemodels to report this as part of their standard functionality, I.e. the difference between training g and test set error.

The error in the treeing set can be calculated during the over-ridden fit() method.
It would require access to the test set.
- would be provided by the researcher if they make a call to run_arttack()
- - or if they provide the dataset object to request_release()

**Comment by simonrnss** [comment]
Gentle suggestion -- can we add more details into these issues so we avoid all the tangle we had at end of previous sprint please!

**Comment by jim-smith** [comment]
@simonrnss fair point.Description provided above
