### ISSUE TITLE
Subsuming the attack args classes within the attack classes

### ISSUE THREAD

**Issue by rpreen** [AI-SDC/AI-SDC#156]
Currently we have: (1) a base `Attack` class that each attack implementation inherits; (2) each attack implementation creates an `*AttackArgs` class to hold a dictionary of arguments and (3) an `*Attack` class that implements a specific class.

Since the arguments are just a dictionary, do we really need classes for the args? Loading a config file (which just reads a JSON file into the dict) could then be placed into the `Attack` class that all inherit? There is a lot of duplicated code with each having to implement its own `*AttackArgs`

**Comment by simonrnss** [comment]
Agree that this is worth doing. Not sure it's a release 1.0.5 thing -- would prefer to keep that for cleaning up fairly vital outstanding things from the previous rushed release?

**Comment by rpreen** [comment]
As part of this refactor, the newly added `ConfigFile` class should probably be removed for simplicity and replaced with either a static function in `attacks.py` or a function added to the `Attack` class.

**Comment by shahzadmumtaz22** [comment]
Agreed - I will prefer a function added to the Attack class.

**Comment by rpreen** [comment]
Something to consider is whether it's a cleaner API for the researcher if we pass the args as a `dict` or [`**kwargs`](https://book.pythontips.com/en/latest/args_and_kwargs.html).
