### ISSUE TITLE
Update dependencies for tensorflow-privacy 0.8.10

### ISSUE THREAD

**Issue by rpreen** [AI-SDC/AI-SDC#184]
[tensorflow-privacy](https://pypi.org/project/tensorflow-privacy/) has released 0.8.10 which breaks our current dependency versioning so we need update the requirements.txt and setup.py

**Comment by rpreen** [comment]
I merged fixes into development and main; also rebuilt v.1.0.5 for pip as 1.0.5.post1 with the new dependency versions - this one locks tensorflow-privacy to 0.8.10 so we don't get sucked into another forced update.

**Comment by jim-smith** [comment]
@rpreen The joy that is tensor flow-privacy ...
At least this version is tied to tensorflow ~= 2.4 which is not too out of date (latest is 2.12)
and numpy ~= 1.21.  (latest current is 1.25)  

It would be interesting to see what it does if you pip install it on a system that already has the newer version. I don't know how the "~" checks for compatibility

**Comment by rpreen** [comment]
We're using the following now, so we do have the newer tensorflow
```
        "dictdiffer~=0.9.0",
        "fpdf~=1.7.2",
        "joblib~=1.1.1",
        "multiprocess~=0.70.12.2",
        "numpy~=1.22.0",
        "pandas~=1.5.3",
        "scikit_learn~=1.1.3",
        "scipy~=1.9.0",
        "tensorflow~=2.12.0",
        "tensorflow_privacy==0.8.10",
        "uuid~=1.30",
```
