### ISSUE TITLE
Likelihood attack reproducibility

### ISSUE THREAD

**Issue by albacrespi** [AI-SDC/AI-SDC#222]
How to make the data splits of the LIRA reproducible? I noticed in the code it used random to generate indices to select rows of data, see line 303

    these_idx = np.random.choice(indices, n_train_rows, replace=False)

Would be saving "these_idx" enough to count as reproducible? Or another way of solving this problem would be, for example, by saving the probabilities calculated by the shadow models (causing a potential issue for disk storage).

Also I noted a comment on lines 324 to 326 saying that some classes might not be represented in the split. Can something be done to avoid it as much as possible?

If we make the data splits reproducible, does LIRA still make sense?

**Comment by jim-smith** [comment]
@albacrespi  @simonrnss can confirm, but I don't think that what LIRA does internally is an issue we need to worry about.
The first 12 minutes of [this video](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjv2deIgOaAAxWvXUEAHdPtBzsQwqsBegQIKhAG&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D1CNxfhMlk-A&usg=AOvVaw3yi8cZ1hXd8GRja9wg5WZ9&opi=89978449)

explain how LIRA works by creating all those random splits internally but they are not relevant to the final output

**Comment by albacrespi** [comment]
Ok. So you you think running LIRA once is enough? and we may need several repetions of the other attacks then?

**Comment by jim-smith** [comment]
I think that we currently have the tooling set up to run multiple runs of the attacks, but I think repeats may note s anything new

**Comment by simonrnss** [comment]
Hi both -- depends on what our goal is in terms of reproducibility?

**Comment by simonrnss** [comment]
Also, the "missing class" thing that you mention -- I don't think that's a problem is it? The code deals with it fine as far as I can see (and avoiding it would be a bit of a combinatorial nightmare)

**Comment by jim-smith** [comment]
Covered by simon's original implementation and by the refactoring in #281
