### ISSUE TITLE
Need to increase the visibility of the user stories

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/AI-SDC#245]
Hi all,
perhaps especially @yolaj-nhs if you have capacity.

I had an ... interesting discussion with one of our TREs yesterday who said the first they had known about the User Stories was when they looked the draft final report.
When I explained what they were, said person was very much 'oh, that's what we needed. all along- both for testing,  and when they are discussing with researchers **before the start** what they need to produce.

Made me realise that they are not very visible so this issue is just to:
- flag them very clearly in the readme on the main repo landing page
- check the wording in the readme within the suer stories directory
- revise the iodagram so the words fit in the boxes and put that at the top of the readme in the user stories directory.

**Comment by yolaj-nhs** [comment]
I've picked this up

**Comment by rpreen** [comment]
This was completed some time ago.
