### ISSUE TITLE
Can the uuid package be removed from dependencies?

### ISSUE THREAD

**Issue by manics** [AI-SDC/AI-SDC#258]
https://pypi.org/project/uuid/ is currently required:
https://github.com/AI-SDC/AI-SDC/blob/fa6c4d62f1274a18dd2044a51e1cf4b252146fd7/requirements.txt#L11

This package was last released Jun 20, 2006

Is it still needed? Is the built-in uuid library good enough? https://docs.python.org/3/library/uuid.html

**Comment by rpreen** [comment]
Removed in #262
