### ISSUE TITLE
pylint cleanup

### ISSUE THREAD

**Issue by rpreen** [AI-SDC/AI-SDC#26]
Need to address the pylint warnings, particularly in the safemodel modules.

**Comment by simonrnss** [comment]
I've added an auto-generated .pylintrc file to branch 26-pylintcleanup and added an additional disable of `invalid-name` which will switch off the variable checking.

To add other disables (although I think we should add disables sparingly), just add them to the disable block in the file

**Comment by simonrnss** [comment]
Also, @rpreen I think if we're using .pylintrc to ignore things, we should change the pylint to fail at a higher threshold. It's currently 7 and I'm going to up it to 9...

**Comment by rpreen** [comment]
Yeah, it would be nice to have the .pylintrc in such a way that it's pass/fail at 10, but maybe that's not possible if it's checking for things like duplicate code and there may be some rare times that's necessary.

**Comment by simonrnss** [comment]
I think 10 is feasible -- just means that people need to explicitly add disable comments on the occasions that pylint is too picky.

I propose we change to 10 once we've got it to 10!
