### ISSUE TITLE
Standardise attack output

### ISSUE THREAD

**Issue by simonrnss** [AI-SDC/AI-SDC#35]
Determine and implement a standard attack output format for all three attack classes (worstcase, likelihood, aia).

**Comment by jim-smith** [comment]
@simonrnss @rpreen @jamesliley 
I have moved location of key:val pair "attack" in worst_case .
So that all three attacks produce a metadata of  dict format:
{"attack": string, "experiment_details": dict, 'global_metrics': dict}

and output that to json.

Do we need to do more at this stage?

**Comment by simonrnss** [comment]
Ah, ok, wrote my email before I saw this. I'm happy with this for now.
