### ISSUE TITLE
Coverage analysis

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/AI-SDC#55]
Should we have coverage analysis built in to the ci tools?

I downloaded the python module coverage and ran 
> coverage run pytest
followed by 
> coverage report -I -m
(the -i told it to skip files it got muddled about)

and got the results below

|Name                                              |    Stmts |  Miss | Cover|   Missing|
|-------------|--------|-------|-------|----------------------------|
|attacks/__init__.py     |                                  0   |   0 |  100%
|attacks/attack.py        |                                 7   |   2   | 71% |  11, 14
|attacks/attribute_attack.py      |                       348  |  298   | 14%  | 39, 45, 49, 56-58, 61, 75, 81-84, 98-112, 118-126, 133-162, 178-206, 211-227, 232-240, 245-275, 282-316, 323-357, 362-367, 374-379, 385-388, 403-409, 452-484, 491-504, 516-521, 528-541, 553-577, 582-613
|attacks/dataset.py        |                               38   |  31   | 18%  | 10-25, 35-39, 43-49, 61-67, 70
|attacks/likelihood_attack.py    |                        247   | 197   | 20%  | 34, 38, 58-62, 75, 79, 83, 88-91, 94, 113-117, 139-159, 237-334, 343-349, 361-384, 398-413, 422-453, 458-498, 504-506, 510-513, 517-520, 526-581, 585
|attacks/metrics.py      |                                 81    |  6   | 93% |  39, 69, 176-179
|attacks/mia_extremecase.py    |                           18   |   1   | 94%  | 78
|attacks/report.py     |                                  158  |  137   | 13%  | 79-85, 90-96, 100-103, 107-109, 113-116, 120-129, 133-178, 206-278, 284, 288-310
|attacks/worst_case_attack.py     |                       186   | 137  |  26% |  45, 49, 53, 58-61, 64, 81-83, 93-95, 114-131, 150-185, 203-236, 244-256, 282-288, 316-318, 336-351, 356-367, 374-387, 391-395, 399-402, 407-558, 561
|preprocessing/loaders.py     |                           251  |  187  |  25%  | 121-129, 134, 136, 138, 140, 142, 148, 150, 152, 154-155, 157, 177-188, 201-209, 221-279, 288-330, 339-369, 379-403, 415-456, 463-616
|safemodel/__init__.py      |                               0   |   0  | 100%
|safemodel/classifiers/__init__.py   |                      6   |   0  | 100%
|safemodel/classifiers/dp_svc.py     |                     96   |  14  |  85%  | 99, 111, 120, 130, 135-136, 190-198
|safemodel/classifiers/safedecisiontreeclassifier.py  |    92   |  29  |  68%  | 34-42, 47-53, 82, 85-87, 89-91, 98-101, 104-109, 115-119, 158, 160
|safemodel/classifiers/safekeras.py      |                226    | 68  |  70%  | 28, 34-43, 50, 56, 62, 77-80, 83-86, 90, 93, 111-112, 117-119, 147, 169, 182-184, 191, 224-229, 243-248, 250-252, 261-263, 277-278, 320-321, 334, 367-372, 384, 405-408, 413-416, 421-424, 432, 453-462, 489, 512-513, 532-553
|safemodel/classifiers/saferandomforestclassifier.py   |   92   |  25  |  73%  | 60-66, 71-72, 76-78, 81-82, 90-95, 102-119
|safemodel/classifiers/safesvc.py        |                 25   |   8  |  68%  | 46-53
|safemodel/classifiers/safetf.py         |                 15    |  4  |  73%  | 19-22
|safemodel/reporting.py                  |                  9    |  1   | 89%  | 73
|safemodel/safemodel.py                |                  336  |  125  |  63%  | 74-77, 120-123, 196-197, 269-270, 278-284, 314, 321, 329-330, 338-357, 370-396, 412-421, 453, 475-482, 524, 557-559, 571, 595, 598-599, 601-602, 606, 608, 619-623, 652, 660, 702-722, 759-760, 773, 775, 786-790, 835-881, 886
|tests/__init__.py                 |                        0    |  0   |  100% |
|tests/test_data_interface.py         |                    25    |  0  | 100% |
|tests/test_metrics.py                  |                  56   |   0  | 100% |
|tests/test_safedecisiontreeclassifier.py    |             97   |   0  | 100% |
|tests/test_safekeras.py                  |               239  |    8  |  97%  | 164, 166, 180, 184, 402, 404, 436, 440
|tests/test_saferandomforestclassifier.py       |          86   |   0  | 100%|
|tests/test_safesvc.py               |                     24   |   0  | 100%|
-----------------------------------------------------------------------------------
|TOTAL    |                                              2758 |  1278 |   54%|

**Comment by jim-smith** [comment]
update after picking some low-hanging fruit: 
I've created a branch extra_tests

Results now:

|Name      |                                            Stmts |  Miss | Cover  | Missing|
|----------|--------------------------------|------|--------|---------|
|attacks/attribute_attack.py       |                      348   | 298   | 14%   |39, 45, 49, 56-58, 61, 75, 81-84, 98-112, 118-126, 133-162, 178-206, 211-227, 232-240, 245-275, 282-316, 323-357, 362-367, 374-379, 385-388, 403-409, 452-484, 491-504, 516-521, 528-541, 553-577, 582-613|
|attacks/dataset.py               |                        38    | 16   | 58%  | 35-39, 43-49, 61-67, 70|
|attacks/likelihood_attack.py  |                         247  |  197   | 20%  | 34, 38, 58-62, 75, 79, 83, 88-91, 94, 113-117, 139-159, 237-334, 343-349, 361-384, 398-413, 422-453, 458-498, 504-506, 510-513, 517-520, 526-581, 585
attacks/metrics.py      |                                81   |   6   | 93%  | 39, 69, 176-179
attacks/mia_extremecase.py       |                        18  |    1   | 94%  | 78
attacks/report.py          |                             158  |  137   | 13%  | 79-85, 90-96, 100-103, 107-109, 113-116, 120-129, 133-178, 206-278, 284, 288-310
attacks/worst_case_attack.py  |                          186  |  137  |  26% |  45, 49, 53, 58-61, 64, 81-83, 93-95, 114-131, 150-185, 203-236, 244-256, 282-288, 316-318, 336-351, 356-367, 374-387, 391-395, 399-402, 407-558, 561
preprocessing/loaders.py               |                 251  |  187  |  25%  | 121-129, 134, 136, 138, 140, 142, 148, 150, 152, 154-155, 157, 177-188, 201-209, 221-279, 288-330, 339-369, 379-403, 415-456, 463-616
safemodel/classifiers/dp_svc.py    |                      96  |   13  |  86%  | 99, 111, 120, 130, 136, 190-198
safemodel/classifiers/ safedecisiontreeclassifier.py   |   92   |  29  |  68%  | 34-42, 47-53, 82, 85-87, 89-91, 98-101, 104-109, 115-119, 158, 160
safemodel/classifiers/ safekeras.py        |              226   |  68  |  70% |  28, 34-43, 50, 56, 62, 77-80, 83-86, 90, 93, 111-112, 117-119, 147, 169, 182-184, 191, 224-229, 243-248, 250-252, 261-263, 277-278, 320-321, 334, 367-372, 384, 405-408, 413-416, 421-424, 432, 453-462, 489, 512-513, 532-553
safemodel/classifiers/ saferandomforestclassifier.py   |   92   |  25   | 73% |  60-66, 71-72, 76-78, 81-82, 90-95, 102-119
safemodel/classifiers/ safesvc.py             |            25   |   8  |  68%  | 46-53
safemodel/safemodel.py                           |       336  |  125  |  63%  | 74-77, 120-123, 196-197, 269-270, 278-284, 314, 321, 329-330, 338-357, 370-396, 412-421, 453, 475-482, 524, 557-559, 571, 595, 598-599, 601-602, 606, 608, 619-623, 652, 660, 702-722, 759-760, 773, 775, 786-790, 835-881, 886
-----------------------------------------------------------------------------------
|TOTAL        |                                          2774   |1247  |  55%|

15 files skipped due to complete coverage.

**Comment by jim-smith** [comment]
**Bother**

This has revealed to me that development is behind main for the safe models classes which now use standardised versions of strings!
As far as I can see the coverage results for everything except the sagfemodels will be right but I need to pull the relevant files from main into extra_tests then push back into development asap

**Comment by jim-smith** [comment]
| Name    |                                              Stmts |  Miss | Cover |  Missing|
|---------|--------------------------------|------|--------|---------|
|attacks/attribute_attack.py |                            348  |  298  |  14%  | 39, 45, 49, 56-58, 61, 75, 81-84, 98-112, 118-126, 133-162, 178-206, 211-227, 232-240, 245-275, 282-316, 323-357, 362-367, 374-379, 385-388, 403-409, 452-484, 491-504, 516-521, 528-541, 553-577, 582-613|
|attacks/dataset.py            |                           38  |   16   | 58%  | 35-39, 43-49, 61-67, 70|
|attacks/likelihood_attack.py   |                         247  |  197   | 20%   |34, 38, 58-62, 75, 79, 83, 88-91, 94, 113-117, 139-159, 237-334, 343-349, 361-384, 398-413, 422-453, 458-498, 504-506, 510-513, 517-520, 526-581, 585
|attacks/metrics.py        |                               81   |   6  |  93%   |39, 69, 176-179
|attacks/mia_extremecase.py    |                           18   |   1   | 94% |  78
|attacks/report.py                     |                  158  |  137 |   13%|   79-85, 90-96, 100-103, 107-109, 113-116, 120-129, 133-178, 206-278, 284, 288-310
|attacks/worst_case_attack.py    |                        186  |  137 |   26% |  45, 49, 53, 58-61, 64, 81-83, 93-95, 114-131, 150-185, 203-236, 244-256, 282-288, 316-318, 336-351, 356-367, 374-387, 391-395, 399-402, 407-558, 561
|preprocessing/loaders.py        |                        251  |  187 |   25%  | 121-129, 134, 136, 138, 140, 142, 148, 150, 152, 154-155, 157, 177-188, 201-209, 221-279, 288-330, 339-369, 379-403, 415-456, 463-616
|safemodel/classifiers/dp_svc.py     |                     96   |   1  |  99%  | 99
|safemodel/classifiers/safedecisiontreeclassifier.py  |    92   |  29  |  68%  | 34-42, 47-53, 82, 85-87, 89-91, 98-101, 104-109, 115-120, 159, 161
|safemodel/classifiers/safekeras.py                      226  |   68  |  70%|   28, 34-43, 50, 56, 62, 77-80, 83-86, 90, 93, 111-112, 117-119, 147, 169, 182-184, 191, 224-229, 243-248, 250-252, 261-263, 277-278, 320-321, 334, 367-372, 384, 405-408, 413-416, 421-424, 432, 453-462, 489, 512-513, 532-553
|safemodel/classifiers/saferandomforestclassifier.py  |    92   |  25  |  73%  | 60-66, 71-72, 76-78, 81-82, 90-95, 102-119
|safemodel/safemodel.py                                  336  |  122  |  64%  | 74-77, 120-123, 196-197, 269-270, 278-284, 314, 321, 329-330, 338-357, 370-396, 412-421, 453, 475-482, 524, 557-559, 571, 595, 598-599, 601-602, 619-623, 652, 702-722, 759-760, 773, 775, 786-790, 835-881, 886
-----------------------------------------------------------------------------------
|TOTAL                                 |                 2834  | 1224  |  57%|

17 files skipped due to complete coverage.

**Comment by jim-smith** [comment]
After lots of refactoring and editing  so **code in safemodels/classifiers all now  passes pylint**

Name                 |                                 Stmts |  Miss | Cover  | Missing
---------|--------|-------|---------|--------------------------------------------------
attacks/attribute_attack.py                     |        348  |  298  |  14% |  39, 45, 49, 56-58, 61, 75, 81-84, 98-112, 118-126, 133-162, 178-206, 211-227, 232-240, 245-275, 282-316, 323-357, 362-367, 374-379, 385-388, 403-409, 452-484, 491-504, 516-521, 528-541, 553-577, 582-613
attacks/dataset.py                                 |      38  |   16  |  58%  | 35-39, 43-49, 61-67, 70
attacks/likelihood_attack.py                |            247  |  197  |  20%  | 34, 38, 58-62, 75, 79, 83, 88-91, 94, 113-117, 139-159, 237-334, 343-349, 361-384, 398-413, 422-453, 458-498, 504-506, 510-513, 517-520, 526-581, 585
attacks/metrics.py                                   |   81   |   6  |  93% |  39, 69, 176-179
attacks/mia_extremecase.py                    |           18   |   1  |  94%  | 78
attacks/report.py                                    |   158   | 137  |  13%  | 79-85, 90-96, 100-103, 107-109, 113-116, 120-129, 133-178, 206-278, 284, 288-310
attacks/worst_case_attack.py                 |           186  |  137  |  26% |  45, 49, 53, 58-61, 64, 81-83, 93-95, 114-131, 150-185, 203-236, 244-256, 282-288, 316-318, 336-351, 356-367, 374-387, 391-395, 399-402, 407-558, 561
preprocessing/loaders.py                    |            251  |  187  |  25%  | 121-129, 134, 136, 138, 140, 142, 148, 150, 152, 154-155, 157, 177-188, 201-209, 221-279, 288-330, 339-369, 379-403, 415-456, 463-616
safemodel/classifiers/dp_svc.py          |                96  |    1  |  99%  | 99
safemodel/classifiers/safedecisiontreeclassifier.py   |   93   |  29  |  69%  | 35-43, 48-54, 83, 86-88, 90-92, 99-102, 105-110, 117-122, 161, 163
safemodel/classifiers/safekeras.py              |        216  |   63  |  71%  | 31, 38-46, 55, 60, 66, 81-84, 87-90, 94, 97, 113-118, 135-136, 147, 173-174, 181-183, 212, 244-245, 289-290, 338-343, 355, 375-378, 383-386, 391-394, 402, 421-429, 456, 479-480, 499-520
safemodel/classifiers/saferandomforestclassifier.py    |  92  |   24  |  74% |  62-68, 73-74, 78-79, 82-83, 91-98, 105-120
safemodel/safemodel.py           |                       336  |  122   | 64%  | 74-77, 120-123, 196-197, 269-270, 278-284, 314, 321, 329-330, 338-357, 370-396, 412-421, 453, 475-482, 524, 557-559, 571, 595, 598-599, 601-602, 619-623, 652, 702-722, 759-760, 773, 775, 786-790, 835-881, 886
-----------------------------------------------------------------------------------
TOTAL              |                                    2823  | 1218   | 57%

17 files skipped due to complete coverage.

**Comment by rpreen** [comment]
I've added this to the CI and added a badge in README.md that tracks the test coverage in the development branch. A bot should also comment on PRs with the coverage.
