### ISSUE TITLE
Enhance tests 

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/AI-SDC#76]

**Comment by jim-smith** [comment]
Could make better use of fixtures and other aspects of pytests to reduce time taken in tests

**Comment by mahaalbashir** [comment]
Make a brief analysis of how good the tests are for:
- The safe model superclass
-  safedecisiontreeclassifier
- saferandomforestclassifier
- test_attacks_via_safemodel

**Comment by yolaj-nhs** [comment]
Some other suggestions of minor improvements that could be made:

- [ ] A lot of the report.py tests happen in test_attacks.py: separate these into a separate test file
- [ ] Test the contents of the attribute inference attack in test_attribute_inference_attack.py
- [ ] The test_parse_boolean_argument in test_failfast is long and hard to read - split these into one function for tests that should fail, and one function for tests that should pass, so it's easier to read what has been tested
- [ ] In test_generate_report.py - test for the contents of the generated file (not just whether they pass/fail)
- [ ] In test_metrics.py - check the results of the calculation, not just pass/fail
- [ ] Remove test_safekeras.old
- [ ] Inside SafeModel - check contents of release request (can we do this?)
- [ ] In test_worst_case_attack.py - check the contents of make_report
- [ ] In test_worst_case_attack.py, change np.testing to pytest for consistency

**Comment by jim-smith** [comment]
Inside SafeModel - check contents of release request (can we do this?)

Yes we can.
@mahaalbashir one for you.

**Comment by yolaj-nhs** [comment]
Work on this has started - in branch enhance_tests

**Comment by yolaj-nhs** [comment]
Closed via PR #205
